### Get User
GET https://localhost/api/v1/user
Content-Type: application/json
Authorization: Bearer {{access}}

### Put User
PUT https://localhost/api/v1/user
Content-Type: application/json
Authorization: Bearer {{access}}

{
  "name": "John Doe",
  "locationId": 3040051
}