services:
  db:
    image: postgres:15
    container_name: tometrics-ktor-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ktoruser
      POSTGRES_PASSWORD: ktorpass
      POSTGRES_DB: tometrics
    volumes:
      - pgdata:/var/lib/postgresql/data

  main:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: tometrics-main
    env_file: .env
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/tometrics
    depends_on:
      - db

  socialgraph:
    build:
      context: .
      dockerfile: services/socialgraph/Dockerfile
      no_cache: true
    container_name: tometrics-socialgraph
    env_file: ./services/socialgraph/.env
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/socialgraph
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: tometrics-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - main
#      - socialgraph

volumes:
  pgdata:
