version: '3.8'
services:
  db:
    image: postgres:15
    container_name: tometrics-ktor-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ktoruser
      POSTGRES_PASSWORD: ktorpass
      POSTGRES_DB: tometrics
    volumes:
      - pgdata:/var/lib/postgresql/data

  socialgraph:
    build:
      context: .
      dockerfile: services/socialgraph/Dockerfile
    container_name: tometrics-socialgraph
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/tometrics
      DATABASE_USER: ktoruser
      DATABASE_PASSWORD: ktorpass
    depends_on:
      - db

volumes:
  pgdata:
