services:
  db:
    image: postgres:15
    container_name: tometrics-ktor-db
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tometrics-network

  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    networks:
      - tometrics-network

  cronjob:
    build:
      context: .
      dockerfile: services/cronjob/Dockerfile
      no_cache: true
    container_name: tometrics-cronjob
    env_file:
      - .env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  email:
    build:
      context: .
      dockerfile: services/email/Dockerfile
      no_cache: true
    container_name: tometrics-email
    env_file:
      - .env
      - ./services/email/.env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  garden:
    build:
      context: .
      dockerfile: services/garden/Dockerfile
      no_cache: true
    container_name: tometrics-garden
    env_file:
      - .env
      - ./services/garden/.env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  media:
    build:
      context: .
      dockerfile: services/media/Dockerfile
      no_cache: true
    container_name: tometrics-media
    env_file:
      - .env
      - ./services/media/.env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  servicediscovery:
    build:
      context: .
      dockerfile: services/servicediscovery/Dockerfile
      no_cache: true
    container_name: tometrics-servicediscovery
    env_file: .env
    networks:
      - tometrics-network

  socialfeed:
    build:
      context: .
      dockerfile: services/socialfeed/Dockerfile
      no_cache: true
    container_name: tometrics-socialfeed
    env_file:
      - .env
      - ./services/socialfeed/.env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  socialgraph:
    build:
      context: .
      dockerfile: services/socialgraph/Dockerfile
      no_cache: true
    container_name: tometrics-socialgraph
    env_file:
      - .env
      - ./services/socialgraph/.env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
      no_cache: true
    container_name: tometrics-user
    env_file:
      - .env
      - ./services/user/.env
    networks:
      - tometrics-network
    depends_on:
      - db
      - servicediscovery

  nginx:
    image: nginx:latest
    container_name: tometrics-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
    networks:
      - tometrics-network
    depends_on:
      - cronjob
      - email
      - garden
      - media
      - servicediscovery
      - socialfeed
      - socialgraph
      - user

volumes:
  pgdata:

networks:
  tometrics-network:
    driver: bridge
