// TypeScript enum definitions for vegetable growing requirements
enum SpacingRequirement {
	VERY_CLOSE = "very_close", // 5-15 cm
	CLOSE = "close", // 15-30 cm
	MODERATE = "moderate", // 30-60 cm
	WIDE = "wide", // 60-90 cm
	VERY_WIDE = "very_wide", // 90+ cm
}

enum SunlightRequirement {
	FULL_SUN = "full_sun",
	PARTIAL_SUN = "partial_sun",
	PARTIAL_SHADE = "partial_shade",
	FULL_SHADE = "full_shade",
}

enum DailySunlightRequirement {
	LOW = "low", // Less than 4 hours
	MEDIUM = "medium", // 4-6 hours
	HIGH = "high", // 6+ hours
}

enum SoilType {
	SANDY = "sandy",
	LOAMY = "loamy",
	CLAY = "clay",
	PEATY = "peaty",
	CHALKY = "chalky",
	SILTY = "silty",
}

enum WaterRequirement {
	LOW = "low", // Drought-tolerant, infrequent watering
	MEDIUM = "medium", // Regular watering, moist but not wet
	HIGH = "high", // Consistently moist, frequent watering
}

enum PlantGrowthHabit {
	DETERMINATE = "determinate", // Bush-type that grows to a certain height and stops
	INDETERMINATE = "indeterminate", // Vining type that continues growing
	BUSH = "bush", // Compact growing habit
	VINING = "vining", // Climbing or sprawling habit
	UPRIGHT = "upright", // Grows straight up with minimal spread
	ROSETTE = "rosette", // Grows in a circular pattern from center
	CLUMPING = "clumping", // Forms clumps or clusters
	SPREADING = "spreading", // Spreads horizontally
	MOUNDING = "mounding", // Forms a mound shape
}

enum GrowingTip {
	PRUNE_SUCKERS = "prune_suckers",
	PROVIDE_SUPPORT = "provide_support",
	MULCH_SOIL = "mulch_soil",
	WATER_AT_BASE = "water_at_base",
	CROP_ROTATION = "crop_rotation",
	HILL_SOIL = "hill_soil",
	PLANT_DEEP = "plant_deep",
	AVOID_LIGHT_EXPOSURE = "avoid_light_exposure",
	HARVEST_AFTER_FLOWERING = "harvest_after_flowering",
	COOL_STORAGE = "cool_storage",
	LOOSEN_SOIL = "loosen_soil",
	THIN_SEEDLINGS = "thin_seedlings",
	CONSISTENT_MOISTURE = "consistent_moisture",
	AVOID_ROCKY_SOIL = "avoid_rocky_soil",
	PREVENT_GREENING = "prevent_greening",
	PLANT_TIPS_UP = "plant_tips_up",
	REDUCE_WATERING_AT_MATURITY = "reduce_watering_at_maturity",
	CURE_AFTER_HARVEST = "cure_after_harvest",
	DAY_LENGTH_SENSITIVE = "day_length_sensitive",
	SUPPORT_WHEN_FRUITING = "support_when_fruiting",
	HARVEST_WHEN_FIRM = "harvest_when_firm",
	PREVENT_BLOSSOM_END_ROT = "prevent_blossom_end_rot",
	PRODUCES_UNTIL_FROST = "produces_until_frost",
	SUCCESSION_PLANTING = "succession_planting",
	DIRECT_SOW = "direct_sow",
	COLD_HARDY = "cold_hardy",
	HEAT_SENSITIVE = "heat_sensitive",
	HEAT_TOLERANT = "heat_tolerant",
	PINCH_FLOWERS = "pinch_flowers",
	DEADHEAD = "deadhead",
	REQUIRES_POLLINATION = "requires_pollination",
	HAND_POLLINATE = "hand_pollinate",
	AVOID_OVERHEAD_WATERING = "avoid_overhead_watering",
	PLANT_IN_BLOCKS = "plant_in_blocks",
	HARVEST_REGULARLY = "harvest_regularly",
	BLANCHING = "blanching",
	ACIDIC_SOIL = "acidic_soil",
	ALKALINE_SOIL = "alkaline_soil",
	DEEP_ROOT_SYSTEM = "deep_root_system",
	SHALLOW_ROOT_SYSTEM = "shallow_root_system",
	MOUND_PLANTING = "mound_planting",
	TRENCH_PLANTING = "trench_planting",
	REQUIRES_STAKING = "requires_staking",
	NITROGEN_FIXING = "nitrogen_fixing",
	CUT_AND_COME_AGAIN = "cut_and_come_again",
	PERENNIAL_CROP = "perennial_crop",
	HARVEST_SELECTIVELY = "harvest_selectively",
	DROUGHT_RESISTANT = "drought_resistant",
	AVOID_TRANSPLANTING = "avoid_transplanting",
	COMPANION_BENEFICIAL = "companion_beneficial",
	SHADE_TOLERANT = "shade_tolerant",
	EARLY_SPRING_CROP = "early_spring_crop",
	FALL_CROP = "fall_crop",
	OVERWINTER = "overwinter",
	COOL_WEATHER_CROP = "cool_weather_crop",
	REMOVE_LOWER_LEAVES = "remove_lower_leaves",
	FERTILE_SOIL = "fertile_soil",
	NEEDS_SUPPORT_CAGE = "needs_support_cage",
	FLOATING_ROW_COVER = "floating_row_cover",
	SLOW_TO_GERMINATE = "slow_to_germinate",
	SOAK_SEEDS = "soak_seeds",
	PINCH_GROWING_TIPS = "pinch_growing_tips",
	STRATIFICATION = "stratification",
	START_INDOORS = "start_indoors",
	LOOSE_SOIL = "loose_soil",
	HARVEST_WHEN_SMALL = "harvest_when_small",
	MINIMAL_COMPANIONS = "minimal_companions",
	FROST_IMPROVES_FLAVOR = "frost_improves_flavor",
	AVOID_HARVESTING_FIRST_YEAR = "avoid_harvesting_first_year",
	REMOVE_FLOWER_STALKS = "remove_flower_stalks",
	DIVIDE_EVERY_FEW_YEARS = "divide_every_few_years",
	DIVIDE_BULBS = "divide_bulbs",
	NEEDS_CONSTANT_MOISTURE = "needs_constant_moisture",
	AQUATIC_FRIENDLY = "aquatic_friendly",
	HARVEST_AFTER_FROST = "harvest_after_frost",
	CONTAIN_SPREAD = "contain_spread",
	NEEDS_SPACE = "needs_space",
	FULL_MATURITY_FOR_STORAGE = "full_maturity_for_storage",
	HARVEST_IN_FALL_OR_SPRING = "harvest_in_fall_or_spring",
	NEEDS_LONG_SEASON = "needs_long_season",
	PROPER_PROCESSING_REQUIRED = "proper_processing_required",
	SUBMERGED_PLANTING = "submerged_planting",
	SPECIAL_GROWING_CONDITIONS = "special_growing_conditions",
	SLOW_GROWING = "slow_growing",
	WAIT_FOR_WARM_SOIL = "wait_for_warm_soil",
	AVOID_RICH_SOIL = "avoid_rich_soil",
	SHALLOW_PLANTING = "shallow_planting",
	EDIBLE_ROOTS_ONLY = "edible_roots_only",
	LONG_GROWING_SEASON = "long_growing_season",
	PREVENT_FLOWERING = "prevent_flowering",
	ACIDIC_FLAVOR = "acidic_flavor",
	CELERY_FLAVOR = "celery_flavor",
	SIMILAR_TO_ARTICHOKE = "similar_to_artichoke",
	INVASIVE_TENDENCIES = "invasive_tendencies",
	PEST_RESISTANT = "pest_resistant",
	COLORFUL_TUBERS = "colorful_tubers",
	PLANT_WHOLE_FRUIT = "plant_whole_fruit",
	PERENNIAL_IN_TROPICS = "perennial_in_tropics",
	MEDICINAL_PROPERTIES = "medicinal_properties",
	EDIBLE_WHEN_YOUNG = "edible_when_young",
	DRY_FOR_SPONGES = "dry_for_sponges",
	ALL_PARTS_EDIBLE = "all_parts_edible",
	NUTRITIOUS_LEAVES = "nutritious_leaves",
	TREE_VEGETABLE = "tree_vegetable",
	PLANT_MULTIPLES = "plant_multiples",
	HARVEST_WHEN_HUSKS_SPLIT = "harvest_when_husks_split",
	REMOVE_HUSKS_BEFORE_USE = "remove_husks_before_use",
	SAPONIN_REMOVAL = "saponin_removal",
	EDIBLE_LEAVES = "edible_leaves",
	GRAIN_AND_LEAF_CROP = "grain_and_leaf_crop",
	QUICK_GROWING = "quick_growing",
	EXCELLENT_COVER_CROP = "excellent_cover_crop",
	ATTRACTS_POLLINATORS = "attracts_pollinators",
	IMPROVES_SOIL = "improves_soil",
	SEED_CLEANING_REQUIRED = "seed_cleaning_required",
	BIRD_PROTECTION_NEEDED = "bird_protection_needed",
	OIL_AND_FIBER_CROP = "oil_and_fiber_crop",
	HARVEST_FOR_SEEDS = "harvest_for_seeds",
	FORCED_FOR_CHICONS = "forced_for_chicons",
	COFFEE_SUBSTITUTE = "coffee_substitute",
	BITTER_FLAVOR = "bitter_flavor",
	MULTIPLE_ROOTS = "multiple_roots",
	SWEET_FLAVOR = "sweet_flavor",
	MULTI_USE_PLANT = "multi_use_plant",
	SPINACH_SUBSTITUTE = "spinach_substitute",
	SLOW_TO_ESTABLISH = "slow_to_establish",
	COASTAL_NATIVE = "coastal_native",
	SALT_TOLERANT = "salt_tolerant",
	HARVEST_STEMS_AND_LEAVES = "harvest_stems_and_leaves",
	HEAT_TOLERANT_BRASSICA = "heat_tolerant_brassica",
	EDIBLE_FLOWERS = "edible_flowers",
	PEST_DETERRENT = "pest_deterrent",
	COLORFUL_LEAVES = "colorful_leaves",
	SELF_SEEDING = "self_seeding",
	HUMIDITY_TOLERANT = "humidity_tolerant",
	MUCILAGINOUS_TEXTURE = "mucilaginous_texture",
	FAST_GROWING = "fast_growing",
	SHORT_DAY_TUBER_FORMATION = "short_day_tuber_formation",
	BIRD_PROTECTION = "bird_protection",
}

// TypeScript interface for vegetable data structure
export type Vegetable = {
	id: number;
	name: string;
	timeToHarvest: number;
	yieldPerPlant: string;
	yieldPerSqM: string;
	companionPlants: string[];
	climateZones: {
		temperate: number[];
		mediterranean: number[];
		continental: number[];
		tropical: number[];
		arid: number[];
	};
	spacing: SpacingRequirement;
	sunlight: SunlightRequirement;
	dailySunlight: DailySunlightRequirement;
	soilType: SoilType[];
	waterRequirement: WaterRequirement;
	growthHabit: PlantGrowthHabit;
	growingTips: GrowingTip[];
};

const vegetables: Vegetable[] = [
	{
		id: 1,
		name: "Tomatoes",
		timeToHarvest: 80,
		yieldPerPlant: "3-5 kg per plant",
		yieldPerSqM: "8-10 kg per m²",
		companionPlants: ["Basil", "Marigold", "Onions", "Carrots", "Chives"],
		climateZones: {
			temperate: [3, 4, 5],
			mediterranean: [2, 3, 4],
			continental: [4, 5],
			tropical: [9, 10, 11],
			arid: [3, 9],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.INDETERMINATE,
		growingTips: [
			GrowingTip.PRUNE_SUCKERS,
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.MULCH_SOIL,
			GrowingTip.WATER_AT_BASE,
			GrowingTip.CROP_ROTATION,
		],
	},
	{
		id: 2,
		name: "Potatoes",
		timeToHarvest: 90,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "4-6 kg per m²",
		companionPlants: ["Beans", "Corn", "Cabbage", "Horseradish", "Marigold"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 3],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [2, 8, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HILL_SOIL,
			GrowingTip.PLANT_DEEP,
			GrowingTip.AVOID_LIGHT_EXPOSURE,
			GrowingTip.HARVEST_AFTER_FLOWERING,
			GrowingTip.COOL_STORAGE,
		],
	},
	{
		id: 3,
		name: "Carrots",
		timeToHarvest: 75,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Onions", "Leeks", "Rosemary", "Sage", "Tomatoes"],
		climateZones: {
			temperate: [2, 3, 4, 7, 8],
			mediterranean: [1, 2, 8, 9],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [1, 9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.LOOSEN_SOIL,
			GrowingTip.THIN_SEEDLINGS,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.AVOID_ROCKY_SOIL,
			GrowingTip.PREVENT_GREENING,
		],
	},
	{
		id: 4,
		name: "Onions",
		timeToHarvest: 100,
		yieldPerPlant: "200-250g per plant",
		yieldPerSqM: "3-4 kg per m²",
		companionPlants: [
			"Carrots",
			"Beets",
			"Chamomile",
			"Lettuce",
			"Strawberries",
		],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PLANT_TIPS_UP,
			GrowingTip.REDUCE_WATERING_AT_MATURITY,
			GrowingTip.HARVEST_AFTER_FLOWERING,
			GrowingTip.CURE_AFTER_HARVEST,
			GrowingTip.DAY_LENGTH_SENSITIVE,
		],
	},
	{
		id: 5,
		name: "Bell Peppers",
		timeToHarvest: 70,
		yieldPerPlant: "2-3 kg per plant",
		yieldPerSqM: "6-8 kg per m²",
		companionPlants: ["Basil", "Carrots", "Onions", "Spinach", "Tomatoes"],
		climateZones: {
			temperate: [3, 4, 5],
			mediterranean: [2, 3, 4],
			continental: [4, 5],
			tropical: [8, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.SUPPORT_WHEN_FRUITING,
			GrowingTip.HARVEST_WHEN_FIRM,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.MULCH_SOIL,
			GrowingTip.PRODUCES_UNTIL_FROST,
		],
	},
	{
		id: 6,
		name: "Cucumbers",
		timeToHarvest: 60,
		yieldPerPlant: "3-6 kg per plant",
		yieldPerSqM: "5-10 kg per m²",
		companionPlants: ["Corn", "Beans", "Peas", "Sunflowers", "Radishes"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [8, 9, 10],
			arid: [2, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.HARVEST_WHEN_FIRM,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.MULCH_SOIL,
			GrowingTip.AVOID_OVERHEAD_WATERING,
		],
	},
	{
		id: 7,
		name: "Lettuce",
		timeToHarvest: 45,
		yieldPerPlant: "150-300g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Carrots",
			"Radishes",
			"Strawberries",
			"Cucumbers",
			"Beets",
		],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [1, 2, 9, 10, 11],
			continental: [3, 4, 8, 9],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.DIRECT_SOW,
			GrowingTip.HARVEST_WHEN_FIRM,
		],
	},
	{
		id: 8,
		name: "Broccoli",
		timeToHarvest: 85,
		yieldPerPlant: "300-600g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beets", "Onions", "Potatoes", "Rosemary", "Sage"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.HARVEST_WHEN_FIRM,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.COOL_STORAGE,
			GrowingTip.CROP_ROTATION,
			GrowingTip.HEAT_SENSITIVE,
		],
	},
	{
		id: 9,
		name: "Spinach",
		timeToHarvest: 40,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: [
			"Strawberries",
			"Peas",
			"Beans",
			"Cauliflower",
			"Cabbage",
		],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [1, 2, 9, 10, 11],
			continental: [3, 4, 8, 9],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.COLD_HARDY,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.DIRECT_SOW,
		],
	},
	{
		id: 10,
		name: "Zucchini",
		timeToHarvest: 50,
		yieldPerPlant: "5-10 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Corn", "Beans", "Nasturtium", "Oregano", "Marigold"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [10, 11],
			arid: [2, 9],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HARVEST_WHEN_FIRM,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.HAND_POLLINATE,
			GrowingTip.REQUIRES_POLLINATION,
			GrowingTip.MULCH_SOIL,
		],
	},
	{
		id: 11,
		name: "Cabbage",
		timeToHarvest: 90,
		yieldPerPlant: "1.5-2 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Celery", "Dill", "Onions", "Potatoes", "Thyme"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.CROP_ROTATION,
			GrowingTip.COLD_HARDY,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.MULCH_SOIL,
		],
	},
	{
		id: 12,
		name: "Eggplant",
		timeToHarvest: 75,
		yieldPerPlant: "3-4 kg per plant",
		yieldPerSqM: "4-6 kg per m²",
		companionPlants: ["Beans", "Marigold", "Thyme", "Peppers", "Spinach"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [8, 9, 10],
			arid: [2, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.MULCH_SOIL,
			GrowingTip.HARVEST_WHEN_FIRM,
		],
	},
	{
		id: 13,
		name: "Sweet Corn",
		timeToHarvest: 80,
		yieldPerPlant: "2-3 ears per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Cucumbers", "Melons", "Peas", "Squash"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 5],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PLANT_IN_BLOCKS,
			GrowingTip.REQUIRES_POLLINATION,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.HARVEST_WHEN_FIRM,
			GrowingTip.HEAT_TOLERANT,
		],
	},
	{
		id: 14,
		name: "Green Beans",
		timeToHarvest: 55,
		yieldPerPlant: "0.5-1 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Corn", "Carrots", "Cauliflower", "Potatoes", "Rosemary"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.AVOID_OVERHEAD_WATERING,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.HARVEST_REGULARLY,
		],
	},
	{
		id: 15,
		name: "Cauliflower",
		timeToHarvest: 70,
		yieldPerPlant: "1-1.5 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Celery", "Onions", "Spinach", "Beets"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.CROP_ROTATION,
			GrowingTip.BLANCHING,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.COLD_HARDY,
		],
	},
	{
		id: 16,
		name: "Radishes",
		timeToHarvest: 25,
		yieldPerPlant: "25-35g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Carrots", "Lettuce", "Spinach", "Peas", "Cucumbers"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4, 8, 9],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DIRECT_SOW,
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.THIN_SEEDLINGS,
			GrowingTip.COLD_HARDY,
		],
	},
	{
		id: 17,
		name: "Kale",
		timeToHarvest: 60,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beets", "Celery", "Cucumber", "Onions", "Potatoes"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [8, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COLD_HARDY,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.MULCH_SOIL,
			GrowingTip.CROP_ROTATION,
		],
	},
	{
		id: 18,
		name: "Garlic",
		timeToHarvest: 240,
		yieldPerPlant: "40-60g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Beets", "Carrots", "Chamomile", "Cucumbers", "Tomatoes"],
		climateZones: {
			temperate: [8, 9, 10],
			mediterranean: [8, 9, 10],
			continental: [8, 9],
			tropical: [4, 5],
			arid: [8, 9],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PLANT_DEEP,
			GrowingTip.PLANT_TIPS_UP,
			GrowingTip.COLD_HARDY,
			GrowingTip.REDUCE_WATERING_AT_MATURITY,
			GrowingTip.CURE_AFTER_HARVEST,
		],
	},
	{
		id: 19,
		name: "Beets",
		timeToHarvest: 65,
		yieldPerPlant: "150-300g per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Broccoli", "Bush Beans", "Cabbage", "Lettuce", "Onions"],
		climateZones: {
			temperate: [2, 3, 4, 7, 8],
			mediterranean: [1, 2, 8, 9],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DIRECT_SOW,
			GrowingTip.THIN_SEEDLINGS,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.AVOID_ROCKY_SOIL,
			GrowingTip.SUCCESSION_PLANTING,
		],
	},
	{
		id: 20,
		name: "Peas",
		timeToHarvest: 60,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Carrots", "Corn", "Cucumber", "Radish", "Turnip"],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.DIRECT_SOW,
			GrowingTip.COLD_HARDY,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.HEAT_SENSITIVE,
		],
	},
	{
		id: 21,
		name: "Asparagus",
		timeToHarvest: 730, // 2 years for first harvest
		yieldPerPlant: "250-500g per plant",
		yieldPerSqM: "1-2 kg per m²",
		companionPlants: ["Basil", "Parsley", "Tomatoes", "Marigold", "Nasturtium"],
		climateZones: {
			temperate: [2, 3],
			mediterranean: [1, 2],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [1, 2],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DEEP_ROOT_SYSTEM,
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.MULCH_SOIL,
			GrowingTip.PLANT_DEEP,
			GrowingTip.HARVEST_SELECTIVELY,
		],
	},
	{
		id: 22,
		name: "Brussels Sprouts",
		timeToHarvest: 100,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beets", "Chamomile", "Dill", "Marigold", "Nasturtium"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [8, 9],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.MULCH_SOIL,
			GrowingTip.REMOVE_LOWER_LEAVES,
			GrowingTip.HEAT_SENSITIVE,
		],
	},
	{
		id: 23,
		name: "Celery",
		timeToHarvest: 100,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "3-4 kg per m²",
		companionPlants: ["Beans", "Cabbage", "Leeks", "Onions", "Tomatoes"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [9, 10],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.FERTILE_SOIL,
			GrowingTip.BLANCHING,
			GrowingTip.COLD_HARDY,
			GrowingTip.MULCH_SOIL,
		],
	},
	{
		id: 24,
		name: "Swiss Chard",
		timeToHarvest: 55,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Cabbage", "Onions", "Radishes", "Tomatoes"],
		climateZones: {
			temperate: [3, 4, 8, 9],
			mediterranean: [2, 3, 9, 10],
			continental: [4, 5, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.COLD_HARDY,
			GrowingTip.SUCCESSION_PLANTING,
		],
	},
	{
		id: 25,
		name: "Turnips",
		timeToHarvest: 50,
		yieldPerPlant: "150-300g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Peas", "Nasturtium", "Beans", "Onions", "Garlic"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DIRECT_SOW,
			GrowingTip.THIN_SEEDLINGS,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.SUCCESSION_PLANTING,
		],
	},
	{
		id: 26,
		name: "Okra",
		timeToHarvest: 60,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Eggplant", "Peppers", "Basil", "Marigold", "Melons"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [2, 3, 4],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.HARVEST_REGULARLY,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.SLOW_TO_GERMINATE,
			GrowingTip.SOAK_SEEDS,
		],
	},
	{
		id: 27,
		name: "Leeks",
		timeToHarvest: 120,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Carrots",
			"Celery",
			"Onions",
			"Strawberries",
			"Tomatoes",
		],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [2, 3, 9],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.TRENCH_PLANTING,
			GrowingTip.BLANCHING,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.HILL_SOIL,
		],
	},
	{
		id: 28,
		name: "Arugula",
		timeToHarvest: 30,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Beans", "Carrots", "Cucumbers", "Lettuce", "Spinach"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [1, 2, 9, 10, 11],
			continental: [3, 4, 8, 9],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.DIRECT_SOW,
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CUT_AND_COME_AGAIN,
		],
	},
	{
		id: 29,
		name: "Sweet Potatoes",
		timeToHarvest: 120,
		yieldPerPlant: "1.5-2.5 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Peas", "Spinach", "Thyme", "Dill"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [3, 4],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.CURE_AFTER_HARVEST,
			GrowingTip.MOUND_PLANTING,
			GrowingTip.LOOSE_SOIL,
		],
	},
	{
		id: 30,
		name: "Parsnips",
		timeToHarvest: 120,
		yieldPerPlant: "150-250g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Garlic", "Onions", "Peas", "Radishes"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [9, 10, 11],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DIRECT_SOW,
			GrowingTip.SLOW_TO_GERMINATE,
			GrowingTip.COLD_HARDY,
			GrowingTip.LOOSE_SOIL,
			GrowingTip.OVERWINTER,
		],
	},
	{
		id: 31,
		name: "Artichokes",
		timeToHarvest: 180,
		yieldPerPlant: "3-5 heads per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Peas", "Sunflowers", "Tarragon", "Thyme", "Mint"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [1, 2, 3],
			continental: [4, 5],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.VERY_WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.DEEP_ROOT_SYSTEM,
			GrowingTip.MULCH_SOIL,
			GrowingTip.HARVEST_SELECTIVELY,
			GrowingTip.DROUGHT_RESISTANT,
		],
	},
	{
		id: 32,
		name: "Kohlrabi",
		timeToHarvest: 60,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beets", "Cucumbers", "Lettuce", "Onions", "Spinach"],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.HARVEST_WHEN_SMALL,
			GrowingTip.CROP_ROTATION,
			GrowingTip.THIN_SEEDLINGS,
		],
	},
	{
		id: 33,
		name: "Rutabaga",
		timeToHarvest: 90,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "3-4 kg per m²",
		companionPlants: ["Beans", "Herbs", "Nasturtium", "Onions", "Peas"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DIRECT_SOW,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.THIN_SEEDLINGS,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.COOL_STORAGE,
		],
	},
	{
		id: 34,
		name: "Bok Choy",
		timeToHarvest: 45,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Carrots", "Chamomile", "Nasturtium", "Onions"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.HARVEST_REGULARLY,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.HEAT_SENSITIVE,
		],
	},
	{
		id: 35,
		name: "Fennel",
		timeToHarvest: 90,
		yieldPerPlant: "250-350g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Dill", "Cilantro", "Mint", "Chamomile", "Sage"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3, 9],
			continental: [4, 5],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.AVOID_TRANSPLANTING,
			GrowingTip.MINIMAL_COMPANIONS,
			GrowingTip.THIN_SEEDLINGS,
			GrowingTip.HARVEST_SELECTIVELY,
		],
	},
	{
		id: 36,
		name: "Endive",
		timeToHarvest: 90,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Brassicas", "Carrots", "Cucumber", "Radishes"],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [8, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.BLANCHING,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.HARVEST_WHEN_FIRM,
		],
	},
	{
		id: 37,
		name: "Collard Greens",
		timeToHarvest: 70,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Celery", "Cucumber", "Onions", "Thyme"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COLD_HARDY,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.CROP_ROTATION,
		],
	},
	{
		id: 38,
		name: "Mustard Greens",
		timeToHarvest: 45,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Brassicas", "Cucumbers", "Lettuce", "Onions"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CONSISTENT_MOISTURE,
		],
	},
	{
		id: 39,
		name: "Radicchio",
		timeToHarvest: 90,
		yieldPerPlant: "300-400g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Carrots", "Cucumbers", "Onions", "Spinach"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.FROST_IMPROVES_FLAVOR,
			GrowingTip.HARVEST_WHEN_FIRM,
		],
	},
	{
		id: 40,
		name: "Rhubarb",
		timeToHarvest: 365, // 1 year for first harvest
		yieldPerPlant: "2-3 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Brassicas", "Garlic", "Onions", "Strawberries"],
		climateZones: {
			temperate: [2, 3],
			mediterranean: [1, 2],
			continental: [3, 4],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.CLUMPING,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.AVOID_HARVESTING_FIRST_YEAR,
			GrowingTip.REMOVE_FLOWER_STALKS,
			GrowingTip.MULCH_SOIL,
			GrowingTip.DIVIDE_EVERY_FEW_YEARS,
		],
	},
	{
		id: 41,
		name: "Shallots",
		timeToHarvest: 100,
		yieldPerPlant: "150-250g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beets", "Carrots", "Chamomile", "Lettuce", "Tomatoes"],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.CLUMPING,
		growingTips: [
			GrowingTip.PLANT_TIPS_UP,
			GrowingTip.REDUCE_WATERING_AT_MATURITY,
			GrowingTip.CURE_AFTER_HARVEST,
			GrowingTip.DIVIDE_BULBS,
			GrowingTip.MULCH_SOIL,
		],
	},
	{
		id: 42,
		name: "Watercress",
		timeToHarvest: 50,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: [
			"Beans",
			"Broccoli",
			"Cabbage",
			"Cauliflower",
			"Radishes",
		],
		climateZones: {
			temperate: [3, 4, 8, 9],
			mediterranean: [2, 3, 9, 10],
			continental: [4, 5, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.NEEDS_CONSTANT_MOISTURE,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.SHADE_TOLERANT,
			GrowingTip.AQUATIC_FRIENDLY,
		],
	},
	{
		id: 43,
		name: "Jerusalem Artichokes",
		timeToHarvest: 150,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumber", "Peas", "Sunflowers"],
		climateZones: {
			temperate: [2, 3],
			mediterranean: [1, 2],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.PLANT_DEEP,
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.HARVEST_AFTER_FROST,
			GrowingTip.CONTAIN_SPREAD,
		],
	},
	{
		id: 44,
		name: "Pumpkins",
		timeToHarvest: 100,
		yieldPerPlant: "5-10 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Corn",
			"Marigold",
			"Nasturtium",
			"Oregano",
			"Sunflowers",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.VERY_WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.REQUIRES_POLLINATION,
			GrowingTip.NEEDS_SPACE,
			GrowingTip.MOUND_PLANTING,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.CURE_AFTER_HARVEST,
		],
	},
	{
		id: 45,
		name: "Winter Squash",
		timeToHarvest: 95,
		yieldPerPlant: "4-8 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Corn",
			"Marigold",
			"Nasturtium",
			"Oregano",
			"Sunflowers",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.VERY_WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.REQUIRES_POLLINATION,
			GrowingTip.NEEDS_SPACE,
			GrowingTip.MOUND_PLANTING,
			GrowingTip.CURE_AFTER_HARVEST,
			GrowingTip.FULL_MATURITY_FOR_STORAGE,
		],
	},
	{
		id: 46,
		name: "Summer Squash",
		timeToHarvest: 50,
		yieldPerPlant: "5-10 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Corn", "Marigold", "Mint", "Nasturtium", "Oregano"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 9],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HARVEST_REGULARLY,
			GrowingTip.REQUIRES_POLLINATION,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.MULCH_SOIL,
			GrowingTip.HARVEST_WHEN_SMALL,
		],
	},
	{
		id: 47,
		name: "Horseradish",
		timeToHarvest: 365, // 1 year
		yieldPerPlant: "0.5-1 kg per plant",
		yieldPerSqM: "1-2 kg per m²",
		companionPlants: [
			"Potatoes",
			"Sweet Potatoes",
			"Broccoli",
			"Brussels Sprouts",
			"Cabbage",
		],
		climateZones: {
			temperate: [2, 3],
			mediterranean: [1, 2],
			continental: [3, 4],
			tropical: [], // Not suitable for tropical
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.DEEP_ROOT_SYSTEM,
			GrowingTip.CONTAIN_SPREAD,
			GrowingTip.PLANT_DEEP,
			GrowingTip.HARVEST_IN_FALL_OR_SPRING,
		],
	},
	{
		id: 48,
		name: "Ginger",
		timeToHarvest: 300,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Beans",
			"Eggplant",
			"Peppers",
			"Sweet Potatoes",
			"Tomatoes",
		],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [1, 2, 3, 4, 5],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.START_INDOORS,
			GrowingTip.FERTILE_SOIL,
			GrowingTip.MULCH_SOIL,
		],
	},
	{
		id: 49,
		name: "Turmeric",
		timeToHarvest: 300,
		yieldPerPlant: "0.5-1 kg per plant",
		yieldPerSqM: "1-2 kg per m²",
		companionPlants: [
			"Beans",
			"Eggplant",
			"Ginger",
			"Peppers",
			"Sweet Potatoes",
		],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [1, 2, 3, 4, 5],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.START_INDOORS,
			GrowingTip.FERTILE_SOIL,
			GrowingTip.MULCH_SOIL,
		],
	},
	{
		id: 50,
		name: "Yams",
		timeToHarvest: 180,
		yieldPerPlant: "2-3 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Melons", "Squash"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [3, 4],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.MOUND_PLANTING,
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.LOOSE_SOIL,
		],
	},
	{
		id: 51,
		name: "Taro",
		timeToHarvest: 200,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Sweet Potatoes", "Yams"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [3, 4],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.NEEDS_CONSTANT_MOISTURE,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.AQUATIC_FRIENDLY,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.SHADE_TOLERANT,
		],
	},
	{
		id: 52,
		name: "Cassava",
		timeToHarvest: 300,
		yieldPerPlant: "2-4 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Sweet Potatoes", "Yams"],
		climateZones: {
			temperate: [], // Not suitable for temperate
			mediterranean: [], // Not suitable for mediterranean
			continental: [], // Not suitable for continental
			tropical: [3, 4, 9, 10],
			arid: [3, 4],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.LOOSE_SOIL,
			GrowingTip.PROPER_PROCESSING_REQUIRED,
		],
	},
	{
		id: 53,
		name: "Lotus Root",
		timeToHarvest: 240,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Aquatic plants",
			"Rice",
			"Water chestnuts",
			"Water spinach",
			"Watercress",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.AQUATIC_FRIENDLY,
			GrowingTip.NEEDS_CONSTANT_MOISTURE,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.SUBMERGED_PLANTING,
			GrowingTip.CONTAIN_SPREAD,
		],
	},
	{
		id: 54,
		name: "Water Chestnuts",
		timeToHarvest: 240,
		yieldPerPlant: "0.5-1 kg per plant",
		yieldPerSqM: "1-2 kg per m²",
		companionPlants: [
			"Aquatic plants",
			"Lotus root",
			"Rice",
			"Water spinach",
			"Watercress",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.AQUATIC_FRIENDLY,
			GrowingTip.SUBMERGED_PLANTING,
			GrowingTip.NEEDS_CONSTANT_MOISTURE,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.CONTAIN_SPREAD,
		],
	},
	{
		id: 55,
		name: "Wasabi",
		timeToHarvest: 730, // 2 years
		yieldPerPlant: "200-250g per plant",
		yieldPerSqM: "0.5-1 kg per m²",
		companionPlants: ["Ferns", "Hostas", "Mint", "Watercress", "Wild ginger"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SHADE,
		dailySunlight: DailySunlightRequirement.LOW,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.CLUMPING,
		growingTips: [
			GrowingTip.NEEDS_CONSTANT_MOISTURE,
			GrowingTip.SHADE_TOLERANT,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.SPECIAL_GROWING_CONDITIONS,
			GrowingTip.SLOW_GROWING,
		],
	},
	{
		id: 56,
		name: "Daikon Radish",
		timeToHarvest: 60,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "4-6 kg per m²",
		companionPlants: ["Carrots", "Cucumbers", "Lettuce", "Peas", "Spinach"],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DEEP_ROOT_SYSTEM,
			GrowingTip.DIRECT_SOW,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.LOOSE_SOIL,
			GrowingTip.AVOID_ROCKY_SOIL,
		],
	},
	{
		id: 57,
		name: "Fava Beans",
		timeToHarvest: 80,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beets", "Carrots", "Celery", "Corn", "Potatoes"],
		climateZones: {
			temperate: [2, 3, 9, 10],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 9],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.DIRECT_SOW,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.FALL_CROP,
			GrowingTip.EARLY_SPRING_CROP,
		],
	},
	{
		id: 58,
		name: "Lima Beans",
		timeToHarvest: 90,
		yieldPerPlant: "500-700g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Corn",
			"Cucumbers",
			"Potatoes",
			"Radishes",
			"Sunflowers",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.WAIT_FOR_WARM_SOIL,
			GrowingTip.DIRECT_SOW,
		],
	},
	{
		id: 59,
		name: "Chickpeas",
		timeToHarvest: 100,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: [
			"Corn",
			"Cucumbers",
			"Eggplant",
			"Potatoes",
			"Sunflowers",
		],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3, 4],
			continental: [4, 5],
			tropical: [10, 11],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.DIRECT_SOW,
			GrowingTip.WAIT_FOR_WARM_SOIL,
			GrowingTip.HEAT_TOLERANT,
		],
	},
	{
		id: 60,
		name: "Lentils",
		timeToHarvest: 90,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "0.5-1 kg per m²",
		companionPlants: ["Carrots", "Cucumbers", "Garlic", "Herbs", "Potatoes"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3, 4],
			continental: [4, 5],
			tropical: [10, 11],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.DIRECT_SOW,
			GrowingTip.AVOID_RICH_SOIL,
			GrowingTip.COOL_WEATHER_CROP,
		],
	},
	{
		id: 61,
		name: "Mung Beans",
		timeToHarvest: 90,
		yieldPerPlant: "150-200g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: [
			"Corn",
			"Cucumbers",
			"Eggplant",
			"Potatoes",
			"Sunflowers",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.DIRECT_SOW,
			GrowingTip.WAIT_FOR_WARM_SOIL,
			GrowingTip.DROUGHT_RESISTANT,
		],
	},
	{
		id: 62,
		name: "Adzuki Beans",
		timeToHarvest: 90,
		yieldPerPlant: "150-200g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: [
			"Corn",
			"Cucumbers",
			"Eggplant",
			"Potatoes",
			"Sunflowers",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.DIRECT_SOW,
			GrowingTip.WAIT_FOR_WARM_SOIL,
			GrowingTip.SHALLOW_PLANTING,
		],
	},
	{
		id: 63,
		name: "Black-eyed Peas",
		timeToHarvest: 70,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: [
			"Corn",
			"Cucumbers",
			"Eggplant",
			"Potatoes",
			"Sunflowers",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.NITROGEN_FIXING,
			GrowingTip.WAIT_FOR_WARM_SOIL,
			GrowingTip.DIRECT_SOW,
		],
	},
	{
		id: 64,
		name: "Jicama",
		timeToHarvest: 150,
		yieldPerPlant: "2-3 kg per plant",
		yieldPerSqM: "3-4 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumbers", "Squash", "Sunflowers"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.EDIBLE_ROOTS_ONLY,
			GrowingTip.WAIT_FOR_WARM_SOIL,
		],
	},
	{
		id: 65,
		name: "Salsify",
		timeToHarvest: 120,
		yieldPerPlant: "150-250g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Carrots", "Lettuce", "Onions", "Parsnips"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [9, 10, 11],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DEEP_ROOT_SYSTEM,
			GrowingTip.COLD_HARDY,
			GrowingTip.LOOSE_SOIL,
			GrowingTip.DIRECT_SOW,
			GrowingTip.FROST_IMPROVES_FLAVOR,
		],
	},
	{
		id: 66,
		name: "Celeriac",
		timeToHarvest: 110,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "3-4 kg per m²",
		companionPlants: ["Beans", "Brassicas", "Leeks", "Onions", "Tomatoes"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.FERTILE_SOIL,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.START_INDOORS,
			GrowingTip.LONG_GROWING_SEASON,
		],
	},
	{
		id: 67,
		name: "Cardoon",
		timeToHarvest: 180,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Onions", "Peas", "Rosemary", "Thyme"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.BLANCHING,
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.LONG_GROWING_SEASON,
			GrowingTip.MULCH_SOIL,
			GrowingTip.FERTILE_SOIL,
		],
	},
	{
		id: 68,
		name: "Romanesco",
		timeToHarvest: 90,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Celery", "Chamomile", "Dill", "Onions"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.FERTILE_SOIL,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CROP_ROTATION,
		],
	},
	{
		id: 69,
		name: "Amaranth",
		timeToHarvest: 45, // For leaves
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Corn", "Cucumbers", "Eggplant", "Onions", "Peppers"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 9],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.DIRECT_SOW,
			GrowingTip.WAIT_FOR_WARM_SOIL,
		],
	},
	{
		id: 70,
		name: "Mizuna",
		timeToHarvest: 40,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beets", "Carrots", "Onions", "Radishes", "Strawberries"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.SUCCESSION_PLANTING,
			GrowingTip.DIRECT_SOW,
			GrowingTip.HEAT_SENSITIVE,
		],
	},
	{
		id: 71,
		name: "Tatsoi",
		timeToHarvest: 45,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beets", "Carrots", "Onions", "Radishes", "Strawberries"],
		climateZones: {
			temperate: [2, 3, 4, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.COLD_HARDY,
			GrowingTip.DIRECT_SOW,
			GrowingTip.SUCCESSION_PLANTING,
		],
	},
	{
		id: 72,
		name: "Mache",
		timeToHarvest: 60,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Beets", "Carrots", "Lettuce", "Onions", "Radishes"],
		climateZones: {
			temperate: [8, 9, 10, 11],
			mediterranean: [10, 11, 0],
			continental: [8, 9, 10],
			tropical: [11, 0, 1],
			arid: [10, 11, 0],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.COLD_HARDY,
			GrowingTip.DIRECT_SOW,
			GrowingTip.FALL_CROP,
			GrowingTip.OVERWINTER,
		],
	},
	{
		id: 73,
		name: "Purslane",
		timeToHarvest: 45,
		yieldPerPlant: "150-200g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Beets", "Carrots", "Cucumbers", "Onions", "Tomatoes"],
		climateZones: {
			temperate: [4, 5, 6, 7],
			mediterranean: [3, 4, 5, 6],
			continental: [4, 5, 6],
			tropical: [3, 4, 5, 9, 10],
			arid: [3, 4, 9],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.DIRECT_SOW,
			GrowingTip.CONTAIN_SPREAD,
		],
	},
	{
		id: 74,
		name: "Sorrel",
		timeToHarvest: 60,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Carrots", "Lettuce", "Onions", "Strawberries", "Thyme"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.CLUMPING,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.PREVENT_FLOWERING,
			GrowingTip.ACIDIC_FLAVOR,
			GrowingTip.CONTAIN_SPREAD,
		],
	},
	{
		id: 75,
		name: "Lovage",
		timeToHarvest: 90,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Celeriac", "Potatoes", "Rhubarb", "Thyme"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.DEEP_ROOT_SYSTEM,
			GrowingTip.CELERY_FLAVOR,
			GrowingTip.DIVIDE_EVERY_FEW_YEARS,
			GrowingTip.CUT_AND_COME_AGAIN,
		],
	},
	{
		id: 76,
		name: "Sunchokes",
		timeToHarvest: 150,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumber", "Peas", "Sunflowers"],
		climateZones: {
			temperate: [2, 3],
			mediterranean: [1, 2],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.INVASIVE_TENDENCIES,
			GrowingTip.CONTAIN_SPREAD,
			GrowingTip.SIMILAR_TO_ARTICHOKE,
			GrowingTip.HARVEST_AFTER_FROST,
		],
	},
	{
		id: 77,
		name: "Yacon",
		timeToHarvest: 240,
		yieldPerPlant: "2-5 kg per plant",
		yieldPerSqM: "4-6 kg per m²",
		companionPlants: ["Beans", "Corn", "Potatoes", "Squash", "Sunflowers"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.HARVEST_AFTER_FROST,
			GrowingTip.CURE_AFTER_HARVEST,
		],
	},
	{
		id: 78,
		name: "Oca",
		timeToHarvest: 210,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Corn", "Peas", "Squash", "Tomatoes"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [
			GrowingTip.DAY_LENGTH_SENSITIVE,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.HARVEST_AFTER_FROST,
		],
	},
	{
		id: 79,
		name: "Mashua",
		timeToHarvest: 210,
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "3-4 kg per m²",
		companionPlants: ["Beans", "Corn", "Peas", "Squash", "Tomatoes"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.PEST_RESISTANT,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.HARVEST_AFTER_FROST,
		],
	},
	{
		id: 80,
		name: "Ulluco",
		timeToHarvest: 210,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Corn", "Peas", "Squash", "Tomatoes"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.COLORFUL_TUBERS,
			GrowingTip.DAY_LENGTH_SENSITIVE,
			GrowingTip.NEEDS_LONG_SEASON,
			GrowingTip.HARVEST_AFTER_FROST,
		],
	},
	{
		id: 81,
		name: "Chayote",
		timeToHarvest: 120,
		yieldPerPlant: "20-30 fruits per plant",
		yieldPerSqM: "5-8 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Nasturtium", "Sunflowers"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.VERY_WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.PLANT_WHOLE_FRUIT,
			GrowingTip.PERENNIAL_IN_TROPICS,
		],
	},
	{
		id: 82,
		name: "Bitter Melon",
		timeToHarvest: 70,
		yieldPerPlant: "10-15 fruits per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Sunflowers", "Tomatoes"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.SOAK_SEEDS,
		],
	},
	{
		id: 83,
		name: "Luffa",
		timeToHarvest: 120,
		yieldPerPlant: "10-15 fruits per plant",
		yieldPerSqM: "3-5 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Sunflowers", "Tomatoes"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.NEEDS_LONG_SEASON,
		],
	},
	{
		id: 84,
		name: "Winged Beans",
		timeToHarvest: 80,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: [
			"Corn",
			"Cucumbers",
			"Eggplant",
			"Sunflowers",
			"Tomatoes",
		],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.NITROGEN_FIXING,
		],
	},
	{
		id: 85,
		name: "Moringa",
		timeToHarvest: 90, // For leaves
		yieldPerPlant: "1-2 kg per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Eggplant", "Peppers", "Tomatoes", "Yams"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0],
			arid: [2, 3, 4],
		},
		spacing: SpacingRequirement.VERY_WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.FAST_GROWING,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.PERENNIAL_IN_TROPICS,
		],
	},
	{
		id: 86,
		name: "Tomatillos",
		timeToHarvest: 70,
		yieldPerPlant: "3-4 kg per plant",
		yieldPerSqM: "4-6 kg per m²",
		companionPlants: ["Basil", "Marigold", "Mint", "Nasturtium", "Onions"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.BUSH,
		growingTips: [GrowingTip.SUPPORT_WHEN_FRUITING, GrowingTip.HEAT_TOLERANT],
	},
	{
		id: 87,
		name: "Quinoa",
		timeToHarvest: 100,
		yieldPerPlant: "15-20g per plant",
		yieldPerSqM: "0.5-1 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumbers", "Squash", "Sunflowers"],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [], // Not ideal for tropical
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.DIRECT_SOW,
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.BIRD_PROTECTION,
		],
	},
	{
		id: 88,
		name: "Amaranth Grain",
		timeToHarvest: 90,
		yieldPerPlant: "50-100g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumbers", "Squash", "Sunflowers"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.DIRECT_SOW,
			GrowingTip.HEAT_TOLERANT,
		],
	},
	{
		id: 89,
		name: "Buckwheat",
		timeToHarvest: 80,
		yieldPerPlant: "10-15g per plant",
		yieldPerSqM: "0.5-1 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Sunflowers", "Tomatoes"],
		climateZones: {
			temperate: [4, 5, 6],
			mediterranean: [3, 4, 5],
			continental: [4, 5, 6],
			tropical: [], // Not ideal for tropical
			arid: [3, 4],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [GrowingTip.QUICK_GROWING, GrowingTip.DIRECT_SOW],
	},
	{
		id: 90,
		name: "Millet",
		timeToHarvest: 90,
		yieldPerPlant: "20-30g per plant",
		yieldPerSqM: "0.3-0.5 kg per m²",
		companionPlants: ["Beans", "Corn", "Marigold", "Sunflowers", "Tomatoes"],
		climateZones: {
			temperate: [4, 5],
			mediterranean: [3, 4],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3, 4],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.LOW,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.DIRECT_SOW,
			GrowingTip.HEAT_TOLERANT,
		],
	},
	{
		id: 91,
		name: "Flax",
		timeToHarvest: 100,
		yieldPerPlant: "10-15g per plant",
		yieldPerSqM: "0.2-0.3 kg per m²",
		companionPlants: [
			"Carrots",
			"Potatoes",
			"Strawberries",
			"Tomatoes",
			"Wheat",
		],
		climateZones: {
			temperate: [3, 4],
			mediterranean: [2, 3],
			continental: [4, 5],
			tropical: [], // Not ideal for tropical
			arid: [2, 3],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [GrowingTip.DIRECT_SOW, GrowingTip.COOL_WEATHER_CROP],
	},
	{
		id: 92,
		name: "Chicory",
		timeToHarvest: 85,
		yieldPerPlant: "300-400g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Carrots", "Onions", "Spinach", "Tomatoes"],
		climateZones: {
			temperate: [2, 3, 7, 8],
			mediterranean: [8, 9, 10],
			continental: [3, 4, 8],
			tropical: [10, 11],
			arid: [9, 10],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.ROSETTE,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.BLANCHING,
			GrowingTip.DIRECT_SOW,
		],
	},
	{
		id: 93,
		name: "Skirret",
		timeToHarvest: 150,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Carrots", "Celery", "Onions", "Parsnips"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.HIGH,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [GrowingTip.PERENNIAL_CROP, GrowingTip.DIVIDE_EVERY_FEW_YEARS],
	},
	{
		id: 94,
		name: "Good King Henry",
		timeToHarvest: 60, // For leaves
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: [
			"Beans",
			"Carrots",
			"Spinach",
			"Strawberries",
			"Tomatoes",
		],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.COLD_HARDY,
			GrowingTip.SLOW_TO_ESTABLISH,
		],
	},
	{
		id: 95,
		name: "Sea Kale",
		timeToHarvest: 90, // For leaves, longer for roots
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Carrots", "Onions", "Peas", "Spinach"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 9, 10],
			continental: [3, 4],
			tropical: [], // Not suitable for tropical
			arid: [], // Not suitable for arid
		},
		spacing: SpacingRequirement.WIDE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.SANDY, SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.CLUMPING,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.BLANCHING,
			GrowingTip.SALT_TOLERANT,
			GrowingTip.SLOW_TO_ESTABLISH,
			GrowingTip.DROUGHT_RESISTANT,
		],
	},
	{
		id: 96,
		name: "Chinese Broccoli",
		timeToHarvest: 60,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Celery", "Onions", "Potatoes", "Spinach"],
		climateZones: {
			temperate: [2, 3, 8, 9],
			mediterranean: [9, 10, 11],
			continental: [3, 4, 8],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.COOL_WEATHER_CROP,
			GrowingTip.HEAT_SENSITIVE,
			GrowingTip.CONSISTENT_MOISTURE,
			GrowingTip.CROP_ROTATION,
			GrowingTip.FERTILE_SOIL,
		],
	},
	{
		id: 97,
		name: "Chives",
		timeToHarvest: 60,
		yieldPerPlant: "100-150g per plant",
		yieldPerSqM: "1-1.5 kg per m²",
		companionPlants: ["Apples", "Carrots", "Grapes", "Roses", "Tomatoes"],
		climateZones: {
			temperate: [2, 3, 4],
			mediterranean: [1, 2, 3],
			continental: [3, 4],
			tropical: [10, 11],
			arid: [1, 2, 9, 10],
		},
		spacing: SpacingRequirement.CLOSE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.CLUMPING,
		growingTips: [
			GrowingTip.PERENNIAL_CROP,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.DIVIDE_EVERY_FEW_YEARS,
			GrowingTip.COMPANION_BENEFICIAL,
			GrowingTip.EDIBLE_FLOWERS,
		],
	},
	{
		id: 98,
		name: "New Zealand Spinach",
		timeToHarvest: 60,
		yieldPerPlant: "300-500g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumbers", "Onions", "Tomatoes"],
		climateZones: {
			temperate: [4, 5, 6],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 9, 10],
			arid: [2, 3],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY, SoilType.SANDY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.SPREADING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.DROUGHT_RESISTANT,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.SOAK_SEEDS,
		],
	},
	{
		id: 99,
		name: "Orach",
		timeToHarvest: 45,
		yieldPerPlant: "200-300g per plant",
		yieldPerSqM: "1.5-2 kg per m²",
		companionPlants: ["Beans", "Carrots", "Corn", "Onions", "Spinach"],
		climateZones: {
			temperate: [3, 4, 5],
			mediterranean: [2, 3, 9, 10],
			continental: [4, 5],
			tropical: [10, 11, 0],
			arid: [9, 10, 11],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.FULL_SUN,
		dailySunlight: DailySunlightRequirement.HIGH,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.UPRIGHT,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.SALT_TOLERANT,
			GrowingTip.DIRECT_SOW,
			GrowingTip.CUT_AND_COME_AGAIN,
			GrowingTip.SPINACH_SUBSTITUTE,
		],
	},
	{
		id: 100,
		name: "Malabar Spinach",
		timeToHarvest: 55,
		yieldPerPlant: "500-750g per plant",
		yieldPerSqM: "2-3 kg per m²",
		companionPlants: ["Beans", "Corn", "Cucumbers", "Eggplant", "Tomatoes"],
		climateZones: {
			temperate: [4, 5, 6],
			mediterranean: [3, 4, 5],
			continental: [4, 5],
			tropical: [3, 4, 5, 9, 10, 11],
			arid: [3, 4],
		},
		spacing: SpacingRequirement.MODERATE,
		sunlight: SunlightRequirement.PARTIAL_SUN,
		dailySunlight: DailySunlightRequirement.MEDIUM,
		soilType: [SoilType.LOAMY],
		waterRequirement: WaterRequirement.MEDIUM,
		growthHabit: PlantGrowthHabit.VINING,
		growingTips: [
			GrowingTip.HEAT_TOLERANT,
			GrowingTip.PROVIDE_SUPPORT,
			GrowingTip.MUCILAGINOUS_TEXTURE,
			GrowingTip.CUT_AND_COME_AGAIN,
		],
	},
];

export default vegetables;
