ktor:
  application:
    modules:
      - com.tometrics.api.services.socialgraph.SocialGraphServiceAppKt.module
  deployment:
    port: 8081

database:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/socialgraph"
  user: "postgres"
  password: "postgres"
  
logging:
  level: INFO