@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0b21ldHJpY3MtdXNlcnMiLCJpc3MiOiJ0b21ldHJpY3MuY29tIiwidXNlcklkIjoxLCJleHAiOjE3NDg2OTUzNjZ9.FvDV_fCO2Z8eQyk1jFJy8nwuTG-x3vi_jIpHxAGCaGM
@refreshToken = 039a7c2e-66f9-4db6-a67f-51563815cbd1

### Register anon
POST http://localhost:8080/api/v1/auth/anon/register
Content-Type: application/json

### Refresh tokens (update tokens after login)
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout (update tokens after login)
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}

