### Verify
GET https://localhost/api/v1/auth/verify
Content-Type: application/json
Authorization: Bearer {{access}}

### Register anon
POST https://localhost/api/v1/auth/anon/register
Content-Type: application/json

### Refresh tokens (update tokens after login)
POST https://localhost/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh}}"
}

### Logout (update tokens after login)
POST https://localhost/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer {{access}}

{
  "refreshToken": "{{refresh}}"
}
