### Get Harvest All
GET https://localhost/api/v1/harvest/all
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Harvest All By PlantingId
GET https://localhost/api/v1/harvest/all?plantingId=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Harvest All By PlantingId
GET https://localhost/api/v1/harvest/all?plantId=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Add Harvest
POST https://localhost/api/v1/harvest/add
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "plantingId": 1,
  "quantity": 10,
  "unit": "UNIT"
}

### Delete Harvest
DELETE https://localhost/api/v1/harvest/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

