@adminAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZXZqb2Jib2FyZC11c2VycyIsImlzcyI6ImRldmpvYmJvYXJkLmNvbSIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJqb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzQ3Njk0MTQ2fQ.oQBiif0_mdVwhvZ9XU8Z5G6O2xhwUeg5IMlbYZnn9E4
@applicantAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZXZqb2Jib2FyZC11c2VycyIsImlzcyI6ImRldmpvYmJvYXJkLmNvbSIsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJqb2hudSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ3Njk0MTk1fQ.3K5CzfqJzQvWCkgolzRJlMDaT0Q2FaCA6Lo3l2KOsBo

### Get all jobs - auth
GET http://localhost:8080/jobs
Authorization: Bearer {{applicantAccessToken}}

### Get all jobs
GET http://localhost:8080/jobs

### Get filtered jobs with all parameters - auth
GET http://localhost:8080/jobs?query=software&experience=mid_level&company=techcorp&remote=hybrid&jobType=full_time&location=new%20york&minSalary=50000&maxSalary=100000
Authorization: Bearer {{applicantAccessToken}}

### Get filtered jobs with all parameters
GET http://localhost:8080/jobs?query=software&experience=mid_level&company=techcorp&remote=hybrid&jobType=full_time&location=new%20york&minSalary=50000&maxSalary=100000

### Get job by ID - auth
GET http://localhost:8080/jobs/2
Authorization: Bearer {{applicantAccessToken}}

### Get job by ID
GET http://localhost:8080/jobs/2

### Insert a new job
POST http://localhost:8080/jobs/insert
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
  "title": "Software Engineer",
  "experience": "MID_LEVEL",
  "company": "TechCorp",
  "remote": "HYBRID",
  "type": "FULL_TIME",
  "location": "New York",
  "minSalary": 60000,
  "maxSalary": 120000
}

### Delete a job by ID
DELETE http://localhost:8080/jobs/2
Authorization: Bearer {{applicantAccessToken}}

### Favorite a job by ID
POST http://localhost:8080/jobs/favorite/2
Authorization: Bearer {{applicantAccessToken}}

### Unfavorite a job by ID
DELETE http://localhost:8080/jobs/favorite/2
Authorization: Bearer {{applicantAccessToken}}

### Apply for job by ID
POST http://localhost:8080/jobapplications/apply/1
Authorization: Bearer {{applicantAccessToken}}

### Get all job applications for requester
GET http://localhost:8080/jobapplications
Authorization: Bearer {{applicantAccessToken}}

### Get all job applications for job
GET http://localhost:8080/jobapplications/job/2
Authorization: Bearer {{applicantAccessToken}}

