@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzcHJvdXRzY291dC11c2VycyIsImlzcyI6InNwcm91dHNjb3V0LmNvbSIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiIiLCJleHAiOjE3NDg0Nzg3NTZ9.kY8daPRAKFipVTwBTSjoDH77HnvVVMJOtCg2fC_ODDA

### Get all plants
GET http://localhost:8080/api/v1/planting/all
Authorization: Bearer {{accessToken}}

### Delete plant by ID
DELETE http://localhost:8080/api/v1/planting/2
Authorization: Bearer {{accessToken}}

### Patch plant by ID
PATCH http://localhost:8080/api/v1/planting/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "newQuantity": 7
}

### Add a new planting
POST http://localhost:8080/api/v1/planting/add
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "plantId": 1,
  "quantity": 5
}

