### Get all plantings
GET http://localhost:8080/api/v1/planting/all
Authorization: Bearer {{accessToken}}

### Delete planting by ID
DELETE http://localhost:8080/api/v1/planting/2
Authorization: Bearer {{accessToken}}

### Patch planting by ID
PATCH http://localhost:8080/api/v1/planting/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "newQuantity": 7
}

### Add a new planting
POST http://localhost:8080/api/v1/planting/add
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "plantId": 1,
  "quantity": 5
}

