### Get User Profile
GET https://localhost/api/v1/user-profile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Put User Profile
PUT https://localhost/api/v1/user-profile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "John Doe",
  "locationId": 3040051
}