name: Run Tests

on:
  pull_request:
    branches:
      - main  # or 'master' or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # or 21, depending on your project

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run tests
        run: ./gradlew test --continue
