name: Run Tests

on:
  pull_request:
    branches:
      - main  # or 'master' or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.github-actions.yml up -d --build

      - name: Wait for app to be healthy
        run: |
          echo "Waiting for app healthcheck..."
          for i in {1..15}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q app))
            echo "App health: $STATUS"
            if [ "$STATUS" == "healthy" ]; then
              break
            fi
            sleep 2
          done

      - name: Run tests
        run: ./gradlew test --continue
